### PR TITLE
add base64 in toString

### PR DESCRIPTION
**Pull request by caub**

### CODE REVIEW

**Comment by emn178** [comment]
After test, I found the implementation with pure javascript to encode base64 that has better performance and compatible. So I will try to add this implementation to next version. Thanks anyway.

**Comment by caub** [comment]
@emn178 Oh performance yes of course, native btoa would be faster, I just wanted to make it work on node too, and not override native one

**Comment by emn178** [comment]
forgot to inform, it supports base64 output after v0.6.0

**Comment by caub** [comment]
Ah nice, I closed it so, thanks

**Pull request closed without merging**
